package com.yb.hd.entity;

// Generated 2017-7-24 15:05:51 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name = "admin", catalog = "zjddatabase")
public class Admin implements java.io.Serializable {

	private String adminUser;
	private String adminpassword;

	public Admin() {
	}

	public Admin(String adminUser, String adminpassword) {
		this.adminUser = adminUser;
		this.adminpassword = adminpassword;
	}

	@Id
	@Column(name = "adminUser", unique = true, nullable = false, length = 20)
	public String getAdminUser() {
		return this.adminUser;
	}

	public void setAdminUser(String adminUser) {
		this.adminUser = adminUser;
	}

	@Column(name = "adminpassword", nullable = false, length = 20)
	public String getAdminpassword() {
		return this.adminpassword;
	}

	public void setAdminpassword(String adminpassword) {
		this.adminpassword = adminpassword;
	}

}
