package com.yb.hd.entity;
// Generated 2017-7-14 17:29:56 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hdhdlist generated by hbm2java
 */
@Entity
@Table(name = "hdhdlist", catalog = "zjddatabase")
public class Hdhdlist implements java.io.Serializable {

	private String did;
	private Date addtime;
	private String uid;
	private Integer hdcount;
	private String hdid;
	private Integer ucount;
	private Integer cjiangcount;
	
	public void setUcount(Integer ucount) {
		this.ucount = ucount;
	}
	
	@Column(name = "ucount")
	public Integer getUcount() {
		return ucount;
	}
	
	public void setCjiangcount(Integer cjiangcount) {
		this.cjiangcount = cjiangcount;
	}
	
	@Column(name = "cjiangcount")
	public Integer getCjiangcount() {
		return cjiangcount;
	}
	
	public Hdhdlist() {
	}

	public Hdhdlist(String did) {
		this.did = did;
	}

	public Hdhdlist(String did, Date addtime, String uid, Integer hdcount,
			String hdid) {
		this.did = did;
		this.addtime = addtime;
		this.uid = uid;
		this.hdcount = hdcount;
		this.hdid = hdid;
	}

	@Id
	@Column(name = "did", unique = true, nullable = false, length = 50)
	public String getDid() {
		return this.did;
	}

	public void setDid(String did) {
		this.did = did;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "addtime", length = 19)
	public Date getAddtime() {
		return this.addtime;
	}

	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

	@Column(name = "uid", length = 50)
	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	@Column(name = "hdcount")
	public Integer getHdcount() {
		return this.hdcount;
	}

	public void setHdcount(Integer hdcount) {
		this.hdcount = hdcount;
	}

	@Column(name = "hdid", length = 50)
	public String getHdid() {
		return this.hdid;
	}

	public void setHdid(String hdid) {
		this.hdid = hdid;
	}

}
