package com.yb.hd.entity;

// Generated 2017-7-8 20:53:35 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hdusertable generated by hbm2java
 */
@Entity
@Table(name = "hdusertable", catalog = "zjddatabase")
public class Hdusertable implements java.io.Serializable {

	private String id;
	private String usertel;
	private Date useraddtime;
	private String ip;
	private String devname;
	private String hdid;

	public Hdusertable() {
	}

	public Hdusertable(String id, String usertel, Date useraddtime, String hdid) {
		this.id = id;
		this.usertel = usertel;
		this.useraddtime = useraddtime;
		this.hdid = hdid;
	}

	public Hdusertable(String id, String usertel, Date useraddtime, String ip,
			String devname, String hdid) {
		this.id = id;
		this.usertel = usertel;
		this.useraddtime = useraddtime;
		this.ip = ip;
		this.devname = devname;
		this.hdid = hdid;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 60)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "usertel", nullable = true, length = 20)
	public String getUsertel() {
		return this.usertel;
	}

	public void setUsertel(String usertel) {
		this.usertel = usertel;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "useraddtime", nullable = true, length = 19)
	public Date getUseraddtime() {
		return this.useraddtime;
	}

	public void setUseraddtime(Date useraddtime) {
		this.useraddtime = useraddtime;
	}

	@Column(name = "ip", length = 50)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "devname", length = 30)
	public String getDevname() {
		return this.devname;
	}

	public void setDevname(String devname) {
		this.devname = devname;
	}

	@Column(name = "hdid", nullable = true, length = 30)
	public String getHdid() {
		return this.hdid;
	}

	public void setHdid(String hdid) {
		this.hdid = hdid;
	}

}
