package com.yb.hd.entity;
// Generated 2017-7-14 17:29:56 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hdyzhongjiang generated by hbm2java
 */
@Entity
@Table(name = "hdyzhongjiang", catalog = "zjddatabase")
public class Hdyzhongjiang implements java.io.Serializable {

	private String yid;
	private String hdid;
	private String usid;
	private Integer num;
	private Date addtime;

	public Hdyzhongjiang() {
	}

	public Hdyzhongjiang(String yid) {
		this.yid = yid;
	}

	public Hdyzhongjiang(String yid, String hdid, String usid, Integer num,
			Date addtime) {
		this.yid = yid;
		this.hdid = hdid;
		this.usid = usid;
		this.num = num;
		this.addtime = addtime;
	}

	@Id
	@Column(name = "yid", unique = true, nullable = false, length = 50)
	public String getYid() {
		return this.yid;
	}

	public void setYid(String yid) {
		this.yid = yid;
	}

	@Column(name = "hdid", length = 50)
	public String getHdid() {
		return this.hdid;
	}

	public void setHdid(String hdid) {
		this.hdid = hdid;
	}

	@Column(name = "usid", length = 50)
	public String getUsid() {
		return this.usid;
	}

	public void setUsid(String usid) {
		this.usid = usid;
	}

	@Column(name = "num")
	public Integer getNum() {
		return this.num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "addtime", length = 19)
	public Date getAddtime() {
		return this.addtime;
	}

	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

}
