package com.yb.hd.entity;
// Generated 2017-7-14 17:29:56 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hduserzilist generated by hbm2java
 */
@Entity
@Table(name = "hduserzilist", catalog = "zjddatabase")
public class Hduserzilist implements java.io.Serializable {

	private String id;
	private String uid;
	private String usetel;
	private Date hjitime;
	private String usname;
	private String usaddr;
	private Integer jiangx;
	private Integer lingjiang;
	private Date ljiangtime;
	private String remark;
	private String hdid;

	public Hduserzilist() {
	}

	public Hduserzilist(String id) {
		this.id = id;
	}

	public Hduserzilist(String id, String uid, String usetel, Date hjitime,
			String usname, String usaddr, Integer jiangx, Integer lingjiang,
			Date ljiangtime, String remark, String hdid) {
		this.id = id;
		this.uid = uid;
		this.usetel = usetel;
		this.hjitime = hjitime;
		this.usname = usname;
		this.usaddr = usaddr;
		this.jiangx = jiangx;
		this.lingjiang = lingjiang;
		this.ljiangtime = ljiangtime;
		this.remark = remark;
		this.hdid = hdid;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 50)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "uid", length = 50)
	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	@Column(name = "usetel", length = 30)
	public String getUsetel() {
		return this.usetel;
	}

	public void setUsetel(String usetel) {
		this.usetel = usetel;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "hjitime", length = 19)
	public Date getHjitime() {
		return this.hjitime;
	}

	public void setHjitime(Date hjitime) {
		this.hjitime = hjitime;
	}

	@Column(name = "usname", length = 50)
	public String getUsname() {
		return this.usname;
	}

	public void setUsname(String usname) {
		this.usname = usname;
	}

	@Column(name = "usaddr", length = 50)
	public String getUsaddr() {
		return this.usaddr;
	}

	public void setUsaddr(String usaddr) {
		this.usaddr = usaddr;
	}

	@Column(name = "jiangx")
	public Integer getJiangx() {
		return this.jiangx;
	}

	public void setJiangx(Integer jiangx) {
		this.jiangx = jiangx;
	}

	@Column(name = "lingjiang")
	public Integer getLingjiang() {
		return this.lingjiang;
	}

	public void setLingjiang(Integer lingjiang) {
		this.lingjiang = lingjiang;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ljiangtime", length = 19)
	public Date getLjiangtime() {
		return this.ljiangtime;
	}

	public void setLjiangtime(Date ljiangtime) {
		this.ljiangtime = ljiangtime;
	}

	@Column(name = "remark", length = 30)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "hdid", length = 10)
	public String getHdid() {
		return this.hdid;
	}

	public void setHdid(String hdid) {
		this.hdid = hdid;
	}

}
